# ACTION Instalar dependencias
name: Pull Request

on: [pull_request]

jobs:
install:
  name: Installing Packages
  runs-on: ubuntu-latest
  steps: 
    - name: Checkout
      uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        width:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

          - name: Install Dependencies
            run: npm install


# ACTINOS codigos mortos
unusedxports: 
  name: Find unused exports (dead code)
  runs-on: ubuntu-latest
  needs: install
  steps: 
    - name: Checkout
      uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        width:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

          - name: Run ts-prune
            run: npx ts-prune